
export const STUDENTS_DATA = [
    // KELAS 8.1
    { name: "AGNI MAURAZITA", className: "8.1" },
    { name: "ALEKSPI BAROS", className: "8.1" },
    { name: "ANISAH KHANSA TAZKIYAH", className: "8.1" },
    { name: "CAROLIN ENJELIKA RAMADANI", className: "8.1" },
    { name: "CUT RATU MELLANI", className: "8.1" },
    { name: "DEVINA AULIA MAHARANI", className: "8.1" },
    { name: "DHAVA MABEN PRATAMA", className: "8.1" },
    { name: "DIAMONDY LUTFIYAH", className: "8.1" },
    { name: "DIAZ FEBIAN PUTRA ANDRYANO", className: "8.1" },
    { name: "EZA ALVARO DAVINSI", className: "8.1" },
    { name: "GADIS ZANIRA", className: "8.1" },
    { name: "KALYANA", className: "8.1" },
    { name: "KEYLA NOVITA SARI", className: "8.1" },
    { name: "KHALISA AMALIA", className: "8.1" },
    { name: "KHARISMA ADELIA PUTRI", className: "8.1" },
    { name: "M KHADAFI RAMADHAN", className: "8.1" },
    { name: "M. AYDISYAH ANUGRAH", className: "8.1" },
    { name: "M. FABIANO HAKIM", className: "8.1" },
    { name: "M. RAFELLO AGSIADI", className: "8.1" },
    { name: "MISAEL KEVIN PAKPAHAN", className: "8.1" },
    { name: "MUHAMMAD SULTAN AGUNG", className: "8.1" },
    { name: "MUTHIA ARIFFAH", className: "8.1" },
    { name: "NABILA ULFARIZAH", className: "8.1" },
    { name: "NADIRA DIENY PUTRI", className: "8.1" },
    { name: "NAZILLA ZALFA VANIERA", className: "8.1" },
    { name: "NINDIA ELIZA", className: "8.1" },
    { name: "RENATA CARISYA RIZKI.S", className: "8.1" },
    { name: "SOFI MAULIDYAH", className: "8.1" },
    { name: "SRI BUNGA AMANDA", className: "8.1" },
    { name: "SYAKILLA ZAHWA FREDITA", className: "8.1" },
    { name: "THATA INDAH LESTARI", className: "8.1" },
    { name: "TIARA ANGGRAINI", className: "8.1" },
    { name: "ADELIA LIDO ZAHRA NASUTION", className: "8.1" },
    { name: "AGUNG REYFAN SIANIPAR", className: "8.1" },
    { name: "AULIA AZZAHRAH AZMI", className: "8.1" },
    { name: "BEKTAN ATHAAULLAH DZAKWAN", className: "8.1" },

    // KELAS 8.6
    { name: "AIDIL EKA PRASETYA", className: "8.6" },
    { name: "ALFITRAH MUNAZZALAH", className: "8.6" },
    { name: "ALISHA LUTHFIYAH", className: "8.6" },
    { name: "ANANTA MUTHIA AZ ZAHRA", className: "8.6" },
    { name: "ANUGRAH RAMADHANI NORIZ", className: "8.6" },
    { name: "AQIL ANWARI", className: "8.6" },
    { name: "AUFFA ABDILLAH ZAHRA", className: "8.6" },
    { name: "CHINTAMI VANADIRA PRADISA", className: "8.6" },
    { name: "DIRRA RAMADHANI PUTRI", className: "8.6" },
    { name: "FANI RARAH ZABILLA", className: "8.6" },
    { name: "JANEVA SARABOVA", className: "8.6" },
    { name: "KAYLA ASYIFA", className: "8.6" },
    { name: "KENISHA AMELIA", className: "8.6" },
    { name: "M. FADIL RAJAB", className: "8.6" },
    { name: "M. NAUFAL RAYYAN ALFARIZI", className: "8.6" },
    { name: "M. RIFQI AL AFFAN", className: "8.6" },
    { name: "M. RIZKY RAFFI AKBAR", className: "8.6" },
    { name: "M. SOPIAN ANUGRAH", className: "8.6" },
    { name: "MUHAMMAD ALVITRAH RAMADHAN", className: "8.6" },
    { name: "MUHAMMAD FADHIL FATKHU RAKHMAN", className: "8.6" },
    { name: "MUHAMMAD FATHAN ALMAISAN", className: "8.6" },
    { name: "MUHAMMAD IQBAL FADLAN ARZUMA", className: "8.6" },
    { name: "MUHAMMAD NAUFAL SYAHRENDI", className: "8.6" },
    { name: "MUHAMMAD ARIB AINUR RIDHO", className: "8.6" },
    { name: "RAAFI RAIHAN JAELANI", className: "8.6" },
    { name: "RAFA PARAMUDYA HADI", className: "8.6" },
    { name: "RHAFAEL MELASKHO YUDISTIRA", className: "8.6" },
    { name: "SATRIA MUHAMMAD RUFFI", className: "8.6" },
    { name: "TIARA", className: "8.6" },
    { name: "VIVIAN THIRZA FARHANA", className: "8.6" },
    { name: "YUNI GUSNITA", className: "8.6" },
    { name: "ZIA SALSABILA", className: "8.6" },
    { name: "MUHAMMAD AZIZUL HAKIEM", className: "8.6" },
    { name: "MUHAMMAD RASTRA ADHYAKSA", className: "8.6" },
    { name: "MUHAMMAD RIFQI", className: "8.6" },
    { name: "A D PUTRA PERMANA", className: "8.6" },
    { name: "AFIQAH ANNISYA RIZQIA", className: "8.6" },
    { name: "ANDINI PUTRI PRAYUDI", className: "8.6" },
    { name: "AS SYIFA", className: "8.6" },
    { name: "ASYILA SALSABILLA NORIZ", className: "8.6" },
    { name: "AURA BINTANG ASY SYIFA", className: "8.6" },
    { name: "AZKA PRIMA PRANAJA", className: "8.6" },
    { name: "CARISSA PUTRI ANDITA", className: "8.6" },
    { name: "DELA AZZAHRA", className: "8.6" },
    { name: "DESI ZAHARA", className: "8.6" },
    { name: "DIMAS ADRIANSAH", className: "8.6" },
    { name: "ENO ANANDYA UTAMI", className: "8.6" },
    { name: "JESSIKA RAMADHANI", className: "8.6" },
    { name: "KENANDA WIJAYA", className: "8.6" },
    { name: "KHALISHAH GHINA DANTY", className: "8.6" },
    { name: "M. ARLES TRIRAMANA DENANTA", className: "8.6" },
    { name: "M.RAFA ALFATIH", className: "8.6" },
    { name: "MUHAMAD IQBAL", className: "8.6" },
    { name: "MUHAMMAD ATHA RAZZAN ALI NAYO", className: "8.6" },
    { name: "MUHAMMAD DZAKIYY ARSANDY", className: "8.6" },
    { name: "MUHAMMAD FARREL ALFARIZ", className: "8.6" },
    { name: "MUHAMMAD ZULHAM ALHAMDY", className: "8.6" },
    { name: "NAJWA SYAFA DANIA", className: "8.6" },
    { name: "NAURA DAFINAH YASIRAH", className: "8.6" },
    { name: "NAZWA RAMADHANI", className: "8.6" },
    { name: "OKTI SIFA TRIADINI", className: "8.6" },
    { name: "QUEENSHA ZHAFIRA GUMAY", className: "8.6" },
    { name: "QORRY RIMA ARDEANIKA", className: "8.6" },
    { name: "TAQQIYAH ULFA KHAIRIYAH", className: "8.6" },
    { name: "WHENNY ASYFHA", className: "8.6" },
    { name: "ZAVIRA HADDA TRIWULANDARI", className: "8.6" },
    { name: "PRINCEZIO FERNANDO", className: "8.6" },
    { name: "RAFI RAZAQ AL GHAFAR", className: "8.6" },
    { name: "RAHMAN WILDAN PRATAMA", className: "8.6" },
    { name: "SERLY PRATIWI LESTARI", className: "8.6" },
];
